version: '3.8'

services:
  nginx:
    build: docker/nginx
    volumes:
      - nginx_logs:/var/log/nginx
      - static_volume:/home/app/notification_planning/static
    ports:
      - "9000:80"
    depends_on:
      - django_app
    networks:
      - notification_planning_network

  redis:
    container_name: redis_celery
    image: redis:6.2.6-alpine
    expose:
      - 6379
    networks:
      - notification_planning_network

  postgres_db:
    container_name: postgres_db
    image: postgres:12.0-alpine
    volumes:
      - notification_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=notification_planning
      - POSTGRES_USER=notification_planning
      - POSTGRES_PASSWORD=notification_planning
    expose:
      - 5432
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready -U notification_planning" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - notification_planning_network

  django_app:
    container_name: notification_app
    build:
      context: .
      dockerfile: docker/notification_planning/Dockerfile
    command: >
      sh -c 'python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000'
    volumes:
      - static_volume:/home/app/notification_planning/static
    expose:
      - 8000
    env_file:
      - docker/notification_planning/example.env
    depends_on:
      postgres_db:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - notification_planning_network

  celery_worker:
    container_name: notification_worker
    build:
      context: .
      dockerfile: docker/notification_planning/Dockerfile
    command: >
      sh -c "celery -A config worker -l info"
    env_file:
      - docker/notification_planning/example.env
    depends_on:
      django_app:
        condition: service_started
    networks:
      - notification_planning_network

  celery_beat:
    container_name: notification_scheduler
    build:
      context: .
      dockerfile: docker/notification_planning/Dockerfile
    command: >
      sh -c "celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    env_file:
      - docker/notification_planning/example.env
    depends_on:
      django_app:
        condition: service_started
    networks:
      - notification_planning_network

  flower:
    container_name: flower
    build:
      context: .
      dockerfile: docker/notification_planning/Dockerfile
    command: >
      sh -c "celery -A config flower"
    ports:
      - "5555:5555"
    env_file:
      - docker/notification_planning/example.env
    networks:
      - notification_planning_network

volumes:
  nginx_logs:
  static_volume:
  notification_postgres_data:

networks:
  notification_planning_network:
    driver: bridge
